# Generated by Django 3.2.9 on 2021-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20211108_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
