# Generated by Django 3.2.9 on 2021-11-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_candidate_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='id_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
