# Generated by Django 3.2.9 on 2021-11-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_candidate_id_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.BooleanField(default=False)),
                ('aviation_role', models.BooleanField(default=False)),
                ('business_development', models.BooleanField(default=False)),
                ('facility_management', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('hospital_administration', models.BooleanField(default=False)),
                ('hrm', models.BooleanField(default=False)),
                ('iot_blockchain_datascience', models.BooleanField(default=False)),
                ('strategy_management', models.BooleanField(default=False)),
                ('operations', models.BooleanField(default=False)),
                ('product_management', models.BooleanField(default=False)),
                ('project_management', models.BooleanField(default=False)),
                ('qa_qc', models.BooleanField(default=False)),
                ('scm', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('technical_content_writing', models.BooleanField(default=False)),
                ('marine_weapons_systems', models.BooleanField(default=False)),
                ('employee_relations', models.BooleanField(default=False)),
                ('occupational_safety', models.BooleanField(default=False)),
                ('legal_compliance', models.BooleanField(default=False)),
                ('education_org', models.BooleanField(default=False)),
                ('it_ites', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='apis.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avionics', models.BooleanField(default=False)),
                ('aviation', models.BooleanField(default=False)),
                ('automobile', models.BooleanField(default=False)),
                ('consultant', models.BooleanField(default=False)),
                ('cyber_security', models.BooleanField(default=False)),
                ('defence_sector', models.BooleanField(default=False)),
                ('e_commerce', models.BooleanField(default=False)),
                ('fmcg', models.BooleanField(default=False)),
                ('health_care', models.BooleanField(default=False)),
                ('infra', models.BooleanField(default=False)),
                ('it_ites', models.BooleanField(default=False)),
                ('logistics', models.BooleanField(default=False)),
                ('pharma_biotech', models.BooleanField(default=False)),
                ('r_and_d', models.BooleanField(default=False)),
                ('service_sector', models.BooleanField(default=False)),
                ('ship_building', models.BooleanField(default=False)),
                ('social_service_sector', models.BooleanField(default=False)),
                ('telecom', models.BooleanField(default=False)),
                ('training', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('semiconductor_design_fab', models.BooleanField(default=False)),
                ('weapon_system', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='apis.candidate')),
            ],
        ),
    ]
