# Generated by Django 3.2.9 on 2021-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_industry_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=150),
        ),
    ]
