# Generated by Django 3.2.9 on 2021-12-21 02:42

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20211124_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('repeat_password', models.CharField(max_length=50, validators=[apis.models.User.minpassword])),
                ('password', models.CharField(max_length=50, validators=[apis.models.User.minpassword])),
                ('isVerified', models.BooleanField(blank=True, default=False, null=True)),
                ('otp', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
