# Generated by Django 3.2.9 on 2021-12-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20211221_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repeat_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
