# Generated by Django 3.2.9 on 2021-12-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20211221_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=1111111111),
            preserve_default=False,
        ),
    ]
